language: csharp
solution: Demo.sln
dist: xenial
sudo: required    
dotnet: 3.0.100
mono: none

services:
  - docker

os:
  - linux
  - osx
  
osx_image: xcode9.1

branches:
  only:
    - master
    - dev
 
script:
  - sudo docker pull redis
  - sudo docker run -p 6379:6379 --name redis6379 -d redis:latest redis-server
  - sudo docker run -p 6380:6379 --name redis6380 -d redis:latest redis-server  
  - if test "$TRAVIS_OS_NAME" == "linux"; then dotnet restore; fi
  - if test "$TRAVIS_OS_NAME" == "osx"; then dotnet restore --disable-parallel; fi
  - dotnet build -c Release
  - if test "$TRAVIS_OS_NAME" == "linux"; then dotnet test -c Release ./Demo.csproj; fi
  - if test "$TRAVIS_OS_NAME" == "osx"; then dotnet test -c Release ./Demo.csproj; fi
